## Creating indexing and manipulating 1D arrays
## Creating indexing and manipulating 2D arrays
## Functions methods and atributes in NumPy
## Probability and statistics with Numpy

NumPy arrays allow for mathimatical arrays over an entire array   Allow for vectorization  Faster than Py lists   Arrays are of single type

1D array in numpy

In [27]:
import numpy as np

In [28]:
x = [150, 200, 300, 450]

In [29]:
x

[150, 200, 300, 450]

In [72]:
y = np.array(x)
y

array([150, 200, 300, 450])

In [73]:
type(y)

numpy.ndarray

In [74]:
type(x)

list

In [75]:
x+x

[150, 200, 300, 450, 150, 200, 300, 450]

In [76]:
x*2

[150, 200, 300, 450, 150, 200, 300, 450]

In [77]:
x*4

[150,
 200,
 300,
 450,
 150,
 200,
 300,
 450,
 150,
 200,
 300,
 450,
 150,
 200,
 300,
 450]

In [78]:
y

array([150, 200, 300, 450])

In [79]:
y+y

array([300, 400, 600, 900])

In [80]:
y*3

array([ 450,  600,  900, 1350])

# Subsetting and Slicing 

In [81]:
y

array([150, 200, 300, 450])

In [82]:
y[0]

150

In [83]:
y[7-6]

200

# Slicing

In [84]:
y[0:3]

array([150, 200, 300])

In [85]:
y[2:4]

array([300, 450])

In [86]:
y[4:5]

array([], dtype=int32)

In [87]:
y[:3]

array([150, 200, 300])

### If you start from zero you dont need to write zero

### Same stuff with a last element, just write like that

In [88]:
y[3:]

array([450])

### If you want to reach the lat element write -1

In [89]:
y[-1]

450

In [90]:
y

array([150, 200, 300, 450])

In [91]:
y[-3:-1]

array([200, 300])

### Last index is not included in PY

# Logical indexing or boolean indexing

In [97]:
y

array([150, 200, 300, 450])

In [98]:
y >200

array([False, False,  True,  True])

# Now we get boolean NumPy array

In [99]:
y  == 300


array([False, False,  True, False])

In [101]:
y != 200

array([ True, False,  True,  True])

>=, <=

In [102]:
y[y > 200]

array([300, 450])

### The upper statement says: give me back those values of y which are greater than 200

### y>200 will give back false false true true, so it will give back only true values