Creating 2D arrays in np

In [1]:
import numpy as np

In [4]:
x = [list(range(0,6)),list(range(9,15)),list(range(20,26))]

In [5]:
x

[[0, 1, 2, 3, 4, 5], [9, 10, 11, 12, 13, 14], [20, 21, 22, 23, 24, 25]]

Now we have a list of list

In [9]:
xnp = np.array(x)

xnp

array([[ 0,  1,  2,  3,  4,  5],
       [ 9, 10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24, 25]])

# Indexing

In [10]:
x[0]

[0, 1, 2, 3, 4, 5]

In [11]:
x[0][1]

1

In [12]:
x[0][-1] 

5

# We take the last element from the first list

In [17]:
xnp[0,-1]

5

# We can write down the index in the same pair of brackets

## In line 17 we say, take the row 0 and then go to the last coloumn 

### Usual python list wont understand that, because it is a list of lists

### Basically, we create a matrix, so we can operate with rows and coloumns

# Slicing

In [18]:
x[0:1]

[[0, 1, 2, 3, 4, 5]]

In [19]:
xnp

array([[ 0,  1,  2,  3,  4,  5],
       [ 9, 10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24, 25]])

In [24]:
xnp[0:2, 1:4]

array([[ 1,  2,  3],
       [10, 11, 12]])

# In previous line in first brackets we slice rows(from 0 to 2) and then coloumns (from 1 to 4)  

In [26]:
xnp[1:3,0:2]

array([[ 9, 10],
       [20, 21]])

## If you will type for example xnp[0], it will give you back the first row

In [27]:
xnp[0]

array([0, 1, 2, 3, 4, 5])

# Logical Indexing

In [29]:
xnp

array([[ 0,  1,  2,  3,  4,  5],
       [ 9, 10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24, 25]])

In [30]:
xnp > 10

array([[False, False, False, False, False, False],
       [False, False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [32]:
xnp[xnp>10]

array([11, 12, 13, 14, 20, 21, 22, 23, 24, 25])

### So basicaly, if you want to get back all the elements which have passed Logical indexing you type :
### xnp[xnp and the logical expression]

### If you are fucusing on 1 row or 1 coloumn, you can do

In [35]:
xnp[:,2]

array([ 2, 11, 22])

In [36]:
xnp[:,2] > 10

array([False,  True,  True])

In [39]:
xnp[:,2][xnp[:,2]>10]

array([11, 22])

## If you want to take bck the values, with respect to the raw and coloumn, you basically chain those 2 expressions from line 35 and 36 

In [40]:
xnp[:,2:5][xnp[:,2:5]>13]

array([22, 23, 24])

In [41]:
xnp

array([[ 0,  1,  2,  3,  4,  5],
       [ 9, 10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24, 25]])

In [42]:
xnp[:,2]

array([ 2, 11, 22])

### If you want to select all the rows from the coloumn you should do:

In [46]:
xnp[:,5]

array([ 5, 14, 25])

### If you want to specify all the coloumns in a specific row you do:

In [47]:
x[2]

[20, 21, 22, 23, 24, 25]

# First entry is the rows, and then coloumns

## If you won't put anything x[2] after 2, it will understand, that you want to work with a whole row

In [50]:
xnp[1,:]

array([ 9, 10, 11, 12, 13, 14])